robotdynid_dataset_recorder:
  ros__parameters:
    output_root: runs
    run_name: ""
    joint_names:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
    joint_state_topic: /joint_states
    urdf_path: examples/sia/sia_v3_urdf.urdf
    duration_sec: 30.0
    min_sample_period_sec: 0.0
    auto_start: true
    shutdown_on_finish: true
    allow_missing_effort: false
