#!/usr/bin/env python3
from robotdynid_ros2.runtime_environment import reexec_with_venv_cmeel

reexec_with_venv_cmeel()

from robotdynid_ros2.trajectory.validate import main  # noqa: E402, I100, I202


if __name__ == "__main__":
    main()
